"use client";

import Link from "next/link";
import Image from "next/image";
import { useState, useSyncExternalStore } from "react";
import { ArrowUpRight, Bookmark, ChevronDown, ChevronRight, Globe2, Play, Plus, Search, SlidersHorizontal, Tag, TrendingUp, Upload } from "lucide-react";
import { categories, sampleVideos } from "@/lib/demo-data";
import { savedServerSnapshot, savedSnapshot, subscribeToSaved, writeSavedIds } from "@/lib/saved";
import type { ShortVideo, SourceMode } from "@/lib/types";

export function HomePage({ videos = sampleVideos, sourceMode = "demo", dataError }: { videos?: ShortVideo[]; sourceMode?: SourceMode; dataError?: string }) {
  const saved = JSON.parse(useSyncExternalStore(subscribeToSaved, savedSnapshot, savedServerSnapshot)) as string[];
  function toggleSave(id: string) {
    const next = saved.includes(id) ? saved.filter((item) => item !== id) : [...saved, id];
    writeSavedIds(next);
  }
  return <>
    <div className="workspace-personalize"><div className="personalize-icon"><SlidersHorizontal size={16} /></div><div><strong>Make these trends personal</strong><span>Connect your YouTube channel and we’ll tune the feed to your niche.</span></div><Link href="/settings" className="text-link">Connect channel <ChevronRight size={14} /></Link></div>
    <section className="trend-workspace-heading"><div><p className="eyebrow">Home / India / Demo mode</p><h1>What’s Trending</h1><p>Discover what’s moving across Indian YouTube Shorts right now.</p></div><div className="heading-actions"><button className="quiet-button"><Upload size={14} /> Export</button><button className="quiet-button"><ArrowUpRight size={14} /> Share</button></div></section>
    <SourceTabs />
    <TrendControls />
    {dataError && <div className="provider-error" role="status"><span>Source unavailable</span><strong>{dataError}</strong><Link href="/settings">Check configuration <ChevronRight size={13} /></Link></div>}
    <div className="workspace-results"><div><span className="green-dot" /> {videos.length} signals found · {sourceMode === "live" ? "Live YouTube evidence" : "Sample fixture"}</div><div className="view-toggle"><button className="view-active">Compact</button><button>Comfortable</button></div></div>
    <div className="video-grid video-grid-wide reference-video-grid">{videos.map((video) => <ShortCard key={video.id} video={video} saved={saved.includes(video.id)} onSave={() => toggleSave(video.id)} />)}</div>
  </>;
}

function SourceTabs() {
  return <div className="source-tabs" role="tablist" aria-label="Trend source"><button className="source-tab-active" role="tab" aria-selected="true"><span className="youtube-glyph">▶</span> YouTube Shorts</button><button role="tab" aria-selected="false" disabled><span className="tiktok-glyph">♪</span> TikTok <small>soon</small></button></div>;
}

function TrendControls() {
  return <section className="trend-controls" aria-label="Trend filters">
    <div className="trend-control-top"><div className="trend-pills"><button className="control-active"><TrendingUp size={13} /> Hot</button><button>Popular</button><button>Latest</button></div><div className="control-actions"><button className="icon-button" aria-label="Grid view" title="Grid view">▦</button><button className="control-active">Compact</button><button>Comfortable</button><button className="control-select">10 <ChevronDown size={13} /></button></div></div>
    <div className="trend-filter-row"><span className="filter-label">FORMAT</span><button>All videos</button><button className="control-active">Shorts</button><button>Long</button><span className="filter-label filter-spacer">TIME WINDOW</span><button>24h</button><button>7d</button><button>30d</button><span className="filter-label filter-spacer">LANGUAGE</span><button className="control-active">English</button><button className="control-select"><Globe2 size={12} /> India <ChevronDown size={12} /></button><label className="category-input"><Search size={13} /><input placeholder="Search a category" aria-label="Search a category" /></label></div>
    <div className="active-filter-row"><span>Active filters</span><span className="active-filter">Language: English <button aria-label="Remove language filter">×</button></span><span className="active-filter">Shorts only <button aria-label="Remove shorts filter">×</button></span><span className="active-filter">India <button aria-label="Remove India filter">×</button></span></div>
  </section>;
}

export function TrendingPage({ videos = sampleVideos, sourceMode = "demo", dataError }: { videos?: ShortVideo[]; sourceMode?: SourceMode; dataError?: string }) {
  const [filter, setFilter] = useState("All signals");
  const filters = ["All signals", "Exploding", "Rising", "Emerging", "Food", "AI & Tech"];
  const shown = videos.filter((video) => filter === "All signals" || video.label === filter || video.category === filter);
  return <><section className="trend-workspace-heading"><div><p className="eyebrow">Discover / India / {sourceMode === "live" ? "Live" : "Demo mode"}</p><h1>What’s Trending</h1><p>Explore the Shorts earning unusual attention right now.</p></div><div className="heading-actions"><button className="quiet-button"><Plus size={14} /> New search</button></div></section><SourceTabs /><TrendControls /><div className="filter-bar secondary-filters">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "filter-active" : ""}>{item}</button>)}</div>{dataError && <div className="provider-error" role="status"><span>Source unavailable</span><strong>{dataError}</strong><Link href="/settings">Check configuration <ChevronRight size={13} /></Link></div>}<div className="workspace-results"><div><span className="green-dot" /> {shown.length} signals found · {sourceMode === "live" ? "Live YouTube evidence" : "Sample fixture"}</div><div className="sample-label">{sourceMode === "live" ? "YouTube" : "Representative sample"}</div></div><div className="video-grid video-grid-wide reference-video-grid">{shown.map((video) => <ShortCard key={video.id} video={video} />)}</div></>;
}

export function CategoriesPage() { return <><PageIntro eyebrow="Intelligence / Pattern map" title="AI categories" description="A living map of the formats people are carrying from one niche into another." action={<button className="quiet-button"><SlidersHorizontal size={14} /> How categories work</button>} /><div className="category-grid category-grid-large">{categories.map((category) => <CategoryPreview key={category.slug} {...category} expanded />)}</div><div className="locked-banner compact"><div><p className="eyebrow">Creator plan</p><h2>Search the map by your niche.</h2><p>Go from a broad category to the exact subtopic worth watching.</p></div><Link href="/search" className="primary-button">Search a niche <ChevronRight size={15} /></Link></div></>; }

export function CategoryPage({ category }: { category: (typeof categories)[number] }) { const related = sampleVideos.filter((video) => video.category === category.name); return <><Link href="/categories" className="back-link">← All categories</Link><PageIntro eyebrow={`AI category / ${category.videoCount.toLocaleString()} signals`} title={category.name} description={category.description} action={<button className="quiet-button"><Bookmark size={14} /> Save category</button>} /><section className="category-hero panel-surface"><div className="category-score" style={{ "--score-color": category.color } as React.CSSProperties}><span>{category.momentum}</span><small>momentum</small></div><div><p className="eyebrow">What is moving inside this category</p><h2>Formats with enough signal to investigate.</h2><p>These are directional estimates from the current sample, not historical growth.</p></div></section><section className="content-section"><SectionHeading eyebrow="Emerging topics" title="Subtopics to watch" /><div className="topic-list">{category.subtopics.map((topic) => <Link href={`/search?query=${encodeURIComponent(topic.name)}`} key={topic.name} className="topic-row"><span className="topic-dot" style={{ backgroundColor: category.color }} /><strong>{topic.name}</strong><span className="topic-status">{topic.status}</span><span className="topic-change">{topic.change}</span><ChevronRight size={15} /></Link>)}</div></section><section className="content-section"><SectionHeading eyebrow="Representative Shorts" title="See the signal" /><div className="video-grid">{related.length ? related.map((video) => <ShortCard key={video.id} video={video} />) : sampleVideos.slice(0, 3).map((video) => <ShortCard key={video.id} video={video} />)}</div></section></>; }

export function ShortCard({ video, saved, onSave }: { video: ShortVideo; saved?: boolean; onSave?: () => void }) { return <article className="short-card"><Link href={`/trending/${video.id}`} className="short-thumb"><Image src={displayThumbnail(video)} alt={video.title} fill sizes="(max-width: 640px) 100vw, (max-width: 1000px) 50vw, 25vw" unoptimized /><span className="thumb-play"><Play size={14} fill="currentColor" /></span><span className={`trend-badge trend-${video.label.toLowerCase()}`}>{video.label}</span><span className="duration">0:{video.durationSeconds}</span></Link><div className="short-body"><div className="short-title-row"><Link href={`/trending/${video.id}`} className="short-title">{video.title}</Link><button className={`save-button ${saved ? "save-active" : ""}`} onClick={onSave} aria-label={saved ? "Remove from saved" : "Save Short"} title={saved ? "Remove from saved" : "Save Short"}><Bookmark size={15} fill={saved ? "currentColor" : "none"} /></button></div><p className="short-channel">{video.channel} <span>·</span> {video.publishedAt}</p><div className="short-stats"><span>{compact(video.views)} views</span><span>{compact(video.likes)} likes</span><span>{compact(video.comments)} comments</span><strong>{compact(video.viewsPerHour)} /h</strong></div><div className="short-footer"><span className="sample-label">{video.sourceMode === "live" ? "Live source" : "Sample fixture"}</span><span className="card-source">YouTube</span></div><div className="short-actions"><button onClick={onSave}><Bookmark size={12} fill={saved ? "currentColor" : "none"} /> {saved ? "Saved" : "Save"}</button><a href={video.sourceUrl} target="_blank" rel="noreferrer">YouTube <ArrowUpRight size={12} /></a><Link href={`/trending/${video.id}`}>Details <ChevronRight size={12} /></Link></div></div></article>; }

function displayThumbnail(video: ShortVideo): string {
  return video.thumbnail.startsWith("/") ? video.thumbnail : `/api/thumbnail?url=${encodeURIComponent(video.thumbnail)}`;
}

function CategoryPreview({ slug, name, description, color, momentum, subtopics, videoCount, expanded }: (typeof categories)[number] & { expanded?: boolean }) { return <Link href={`/categories/${slug}`} className={`category-card ${expanded ? "category-card-expanded" : ""}`}><div className="category-top"><span className="category-icon" style={{ color, borderColor: `${color}55` }}><Tag size={15} /></span><span className="category-momentum" style={{ color }}>+{momentum}%</span></div><h3>{name}</h3><p>{description}</p><div className="category-subtopics">{subtopics.map((topic) => <span key={topic.name}>{topic.name} <b>{topic.change}</b></span>)}</div><div className="category-bottom"><span>{videoCount.toLocaleString()} Shorts</span><span>Explore <ChevronRight size={13} /></span></div></Link>; }
function SectionHeading({ eyebrow, title, link, linkLabel }: { eyebrow: string; title: string; link?: string; linkLabel?: string }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{link && <Link href={link} className="text-link">{linkLabel} <ChevronRight size={14} /></Link>}</div>; }
export function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function compact(value: number) { return value >= 1000000 ? `${(value / 1000000).toFixed(1)}M` : value >= 1000 ? `${Math.round(value / 1000)}K` : value.toString(); }
