"use client";

import Link from "next/link";
import Image from "next/image";
import { useState, useSyncExternalStore } from "react";
import { Activity, BarChart3, Bookmark, ChevronDown, ChevronRight, Clock3, ExternalLink, Eye, Grid2X2, Heart, List, LockKeyhole, MessageCircle, Music2, Play, Search, Tag, TrendingUp, Video } from "lucide-react";
import { categories, sampleVideos } from "@/lib/demo-data";
import { savedServerSnapshot, savedSnapshot, subscribeToSaved, writeSavedIds } from "@/lib/saved";
import type { ShortVideo, SourceMode } from "@/lib/types";

export function HomePage({ videos = sampleVideos, sourceMode = "demo", dataError }: { videos?: ShortVideo[]; sourceMode?: SourceMode; dataError?: string }) {
  const saved = JSON.parse(useSyncExternalStore(subscribeToSaved, savedSnapshot, savedServerSnapshot)) as string[];
  function toggleSave(id: string) {
    const next = saved.includes(id) ? saved.filter((item) => item !== id) : [...saved, id];
    writeSavedIds(next);
  }
  const modeLabel = sourceMode === "live" ? "Observed YouTube evidence" : "Demo mode / Sample fixture";
  const topVideo = videos[0] ?? sampleVideos[0];
  const risingCount = videos.filter((video) => ["Exploding", "Rising"].includes(video.label)).length;
  return <>
    <section className="momentum-home-head"><div><p className="eyebrow">MOMENTUM / INDIA / YOUTUBE SHORTS</p><h1>What&apos;s moving in India</h1><p>The Shorts gaining unusual attention, organized by velocity, creator context, topic, and action.</p></div><Link href="/trending" className="primary-button">Start scanning <ChevronRight size={14} /></Link></section>
    <div className="signal-strip" aria-label="India Shorts signal summary"><div className="metric-cell"><p>Shorts tracked</p><strong>{videos.length}</strong><small>{modeLabel}</small></div><div className="metric-cell metric-accent"><p>Momentum rising</p><strong>{risingCount}</strong><small>Exploding or rising</small></div><div className="metric-cell"><p>Emerging niches</p><strong>{categories.length}</strong><small>Creator markets</small></div><div className="metric-cell"><p>Freshness</p><strong>{sourceMode === "live" ? "Now" : "Sample"}</strong><small>No fake real-time claims</small></div></div>
    {dataError && <div className="provider-error" role="status"><span>Source unavailable</span><strong>{dataError}</strong><Link href="/settings">Check configuration <ChevronRight size={13} /></Link></div>}
    <section className="home-lead-grid"><article className="lead-signal panel-surface"><div className="lead-copy"><p className="eyebrow">Top signal</p><h2>{topVideo.title}</h2><p>{topVideo.why}</p><div className="lead-meta"><span>{topVideo.channel}</span><span>{compact(topVideo.views)} views</span><span>{compact(topVideo.viewsPerHour)}/h</span><span>{topVideo.engagement}% engagement</span></div></div><Link href={`/trending/${topVideo.id}`} className="lead-thumb"><Image src={displayThumbnail(topVideo)} alt={topVideo.title} fill sizes="260px" unoptimized priority /><span className={`trend-badge trend-${topVideo.label.toLowerCase()}`}>{topVideo.label}</span></Link></article><aside className="market-brief panel-surface"><SectionHeading eyebrow="Market brief" title="What to inspect first" /><div className="brief-list">{videos.slice(0, 4).map((video, index) => <Link href={`/trending/${video.id}`} className="brief-row" key={video.id}><span className="rank-token">#{index + 1}</span><div><strong>{video.topic}</strong><small>{video.category} / {video.format}</small></div><em>{video.velocity ? `+${video.velocity}%` : "First"}</em></Link>)}</div></aside></section>
    <section className="content-section"><SectionHeading eyebrow="Rising now" title="Top Shorts right now" link="/trending" linkLabel="Open feed" /><div className="video-grid video-grid-wide reference-video-grid">{videos.slice(0, 4).map((video, index) => <ShortCard key={video.id} rank={index + 1} video={video} saved={saved.includes(video.id)} onSave={() => toggleSave(video.id)} />)}</div></section>
    <section className="content-section"><SectionHeading eyebrow="Creator markets" title="Content niches" link="/categories" linkLabel="Explore niches" /><div className="category-grid">{categories.slice(0, 4).map((category) => <CategoryPreview key={category.slug} {...category} />)}</div></section>
    <section className="locked-banner"><div><p className="eyebrow">Premium intelligence</p><h2>City, creator, historical, and competitor signals are visible but locked.</h2><p>MOMENTUM tracks India-wide Shorts today. Local and historical layers stay locked until there is evidence behind them.</p></div><Link href="/pricing" className="quiet-button"><LockKeyhole size={14} /> View plans</Link></section>
  </>;
}

function SourceTabs() {
  return <div className="source-tabs" role="tablist" aria-label="Trend source"><button className="source-tab-active" role="tab" aria-selected="true"><Video size={13} /> YouTube Shorts</button><button role="tab" aria-selected="false" disabled><Music2 size={13} /> TikTok <small>soon</small></button><button role="tab" aria-selected="false" disabled><Music2 size={13} /> Instagram <small>soon</small></button></div>;
}

function TrendControls() {
  const categoryFilters = ["All", "Gaming", "AI & Tech", "Entertainment", "Music", "Food", "Fitness", "Education", "Finance"];
  return <section className="trend-controls" aria-label="Trend filters">
    <div className="trend-control-top"><div className="trend-pills"><button className="control-active"><TrendingUp size={13} /> Hot</button><button><BarChart3 size={13} /> Popular</button><button><Clock3 size={12} /> Latest</button></div><div className="control-actions"><button className="icon-button control-active" aria-label="Grid view" title="Grid view"><Grid2X2 size={13} /></button><button className="icon-button" aria-label="List view" title="List view"><List size={13} /></button><button className="control-active">Compact</button><button>Comfortable</button><button className="control-select">10 <ChevronDown size={13} /></button></div></div>
    <div className="trend-filter-row"><span className="filter-label">FORMAT</span><button>All videos</button><button className="control-active">Shorts</button><button>Long</button><span className="filter-label filter-spacer">TIME WINDOW</span><button>24h</button><button>3d</button><button className="control-active">7d</button><button>14d</button><button className="locked-filter" disabled>30d <LockKeyhole size={10} /></button><span className="filter-label filter-spacer">LANGUAGE</span><button>All</button><button className="control-active">English</button><button>Hindi</button><button>Hinglish</button><button>Regional</button><span className="filter-label filter-spacer">REGION</span><button className="control-active">India</button></div>
    <div className="category-filter-row"><span className="filter-label">CATEGORY</span>{categoryFilters.map((item) => <button key={item} className={item === "All" ? "control-active" : ""}>{item}</button>)}</div>
    <div className="active-filter-row"><span>Active filters</span><span className="active-filter">English <button aria-label="Remove language filter">x</button></span><span className="active-filter">Shorts only <button aria-label="Remove shorts filter">x</button></span><span className="active-filter">India <button aria-label="Remove India filter">x</button></span></div>
  </section>;
}

export function TrendingPage({ videos = sampleVideos, sourceMode = "demo", dataError }: { videos?: ShortVideo[]; sourceMode?: SourceMode; dataError?: string }) {
  const [filter, setFilter] = useState("All signals");
  const filters = ["All signals", "Exploding", "Rising", "Emerging", "Stable", "Food", "AI & Tech"];
  const shown = videos.filter((video) => filter === "All signals" || video.label === filter || video.category === filter);
  return <><section className="trend-workspace-heading"><div><p className="eyebrow">DISCOVER / INDIA / {sourceMode === "live" ? "OBSERVED" : "DEMO MODE"}</p><h1>What&apos;s Trending</h1><p>Explore the Shorts earning unusual attention right now.</p></div><Link href="/search" className="quiet-button"><Search size={14} /> Search niche</Link></section><SourceTabs /><TrendControls /><div className="filter-bar secondary-filters">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "filter-active" : ""}>{item}</button>)}</div>{dataError && <div className="provider-error" role="status"><span>Source unavailable</span><strong>{dataError}</strong><Link href="/settings">Check configuration <ChevronRight size={13} /></Link></div>}<div className="workspace-results"><div><span className="green-dot" /> {shown.length} signals found <span>/</span> {sourceMode === "live" ? "Observed YouTube evidence" : "Sample fixture"}</div><div className="sample-label">YOUTUBE</div></div><div className="video-grid video-grid-wide reference-video-grid">{shown.map((video, index) => <ShortCard key={video.id} rank={index + 1} video={video} />)}</div></>;
}

export function CategoriesPage() { return <><PageIntro eyebrow="INTELLIGENCE / CREATOR MARKETS" title="Content Niches" description="A compact map of the categories, formats, and topics carrying attention across Indian Shorts." action={<Link href="/search" className="quiet-button"><Search size={14} /> Search niche</Link>} /><div className="category-grid category-grid-large">{categories.map((category) => <CategoryPreview key={category.slug} {...category} expanded />)}</div><div className="locked-banner compact"><div><p className="eyebrow">Historical intelligence</p><h2>Track how a niche developed over 30 days.</h2><p>Longer history is a premium layer. It is locked until there are repeated observations behind it.</p></div><Link href="/pricing" className="primary-button">Unlock intelligence <ChevronRight size={15} /></Link></div></>; }

export function CategoryPage({ category }: { category: (typeof categories)[number] }) { const related = sampleVideos.filter((video) => video.category === category.name); return <><Link href="/categories" className="back-link">← All niches</Link><PageIntro eyebrow={`Niche intelligence / ${category.videoCount.toLocaleString()} signals`} title={category.name} description={category.description} action={<button className="quiet-button"><Bookmark size={14} /> Save niche</button>} /><section className="category-hero panel-surface"><div className="category-score" style={{ "--score-color": category.color } as React.CSSProperties}><span>{category.momentum}</span><small>momentum</small></div><div><p className="eyebrow">What is moving inside this niche</p><h2>Formats with enough signal to investigate.</h2><p>These are directional estimates from the current sample, not historical growth.</p></div></section><section className="content-section"><SectionHeading eyebrow="Emerging topics" title="Subtopics to watch" /><div className="topic-list">{category.subtopics.map((topic) => <Link href={`/search?query=${encodeURIComponent(topic.name)}`} key={topic.name} className="topic-row"><span className="topic-dot" style={{ backgroundColor: category.color }} /><strong>{topic.name}</strong><span className="topic-status">{topic.status}</span><span className="topic-change">{topic.change}</span><ChevronRight size={15} /></Link>)}</div></section><section className="content-section"><SectionHeading eyebrow="Representative Shorts" title="See the signal" /><div className="video-grid">{related.length ? related.map((video, index) => <ShortCard key={video.id} rank={index + 1} video={video} />) : sampleVideos.slice(0, 3).map((video, index) => <ShortCard key={video.id} rank={index + 1} video={video} />)}</div></section></>; }

export function ShortCard({ video, rank, saved, onSave }: { video: ShortVideo; rank?: number; saved?: boolean; onSave?: () => void }) {
  const savedIds = JSON.parse(useSyncExternalStore(subscribeToSaved, savedSnapshot, savedServerSnapshot)) as string[];
  const isSaved = saved ?? savedIds.includes(video.id);
  function toggleSave() {
    if (onSave) return onSave();
    const next = isSaved ? savedIds.filter((item) => item !== video.id) : [...savedIds, video.id];
    writeSavedIds(next);
  }
  const tags = [video.category, video.topic, video.format].filter(Boolean).slice(0, 3);
  return <article className="short-card"><Link href={`/trending/${video.id}`} className="short-thumb"><Image src={displayThumbnail(video)} alt={video.title} fill sizes="(max-width: 640px) 100vw, (max-width: 1100px) 50vw, 25vw" unoptimized priority={Boolean(rank && rank <= 4)} /><div className="short-thumb-top"><span>#{rank ?? "-"}</span><strong>{video.velocity > 0 ? `+${video.velocity}%` : "First observation"}</strong></div><span className="thumb-play"><Play size={13} fill="currentColor" /></span><span className="duration">{formatDuration(video.durationSeconds)}</span></Link><div className="short-body"><div className="short-title-row"><Link href={`/trending/${video.id}`} className="short-title">{video.title}</Link><button className={`save-button ${isSaved ? "save-active" : ""}`} onClick={toggleSave} aria-label={isSaved ? "Remove from saved" : "Save Short"} title={isSaved ? "Remove from saved" : "Save Short"}><Bookmark size={15} fill={isSaved ? "currentColor" : "none"} /></button></div><p className="short-channel"><span className="channel-dot" />{video.channel}<span>/</span>{video.publishedAt}</p><div className="short-metrics"><span><Eye size={13} /> {compact(video.views)}</span><span><Heart size={13} /> {compact(video.likes)}</span><span><MessageCircle size={13} /> {compact(video.comments)}</span></div><div className="velocity-row"><Activity size={13} /><strong>{compact(video.viewsPerHour)} views/hour</strong><span>{video.engagement}% engagement</span></div><div className="short-tags"><span className={`trend-badge trend-${video.label.toLowerCase()}`}>{video.label}</span>{tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="short-actions"><button onClick={toggleSave}><Bookmark size={12} fill={isSaved ? "currentColor" : "none"} /> {isSaved ? "Saved" : "Save"}</button><a href={video.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={12} /> YouTube</a><Link href={`/trending/${video.id}`}>Details <ChevronRight size={12} /></Link></div></div></article>;
}

function displayThumbnail(video: ShortVideo): string {
  return video.thumbnail.startsWith("/") ? video.thumbnail : `/api/thumbnail?url=${encodeURIComponent(video.thumbnail)}`;
}

function CategoryPreview({ slug, name, description, color, momentum, subtopics, videoCount, expanded }: (typeof categories)[number] & { expanded?: boolean }) { return <Link href={`/categories/${slug}`} className={`category-card ${expanded ? "category-card-expanded" : ""}`}><div className="category-top"><span className="category-icon" style={{ color, borderColor: `${color}55` }}><Tag size={15} /></span><span className="category-momentum" style={{ color }}>+{momentum}% momentum</span></div><h3>{name}</h3><p>{description}</p><div className="category-subtopics">{subtopics.map((topic) => <span key={topic.name}>{topic.name} <b>{topic.change}</b></span>)}</div><div className="category-bottom"><span>{videoCount.toLocaleString()} signals</span><span>Explore <ChevronRight size={13} /></span></div></Link>; }
function SectionHeading({ eyebrow, title, link, linkLabel }: { eyebrow: string; title: string; link?: string; linkLabel?: string }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{link && <Link href={link} className="text-link">{linkLabel} <ChevronRight size={14} /></Link>}</div>; }
export function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function compact(value: number) { return value >= 1000000 ? `${(value / 1000000).toFixed(1)}M` : value >= 1000 ? `${Math.round(value / 1000)}K` : value.toString(); }
function formatDuration(seconds: number) { return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }
