"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, useSyncExternalStore } from "react";
import { Bookmark, Check, ChevronRight, Copy, ExternalLink, LockKeyhole, PenLine, Play, RefreshCw, Search } from "lucide-react";
import { sampleVideos } from "@/lib/demo-data";
import { savedServerSnapshot, savedSnapshot, subscribeToSaved, writeSavedIds } from "@/lib/saved";
import { getDailyUsage, plans } from "@/lib/entitlements";
import type { ShortVideo, SourceMode } from "@/lib/types";
import { PageIntro, ShortCard } from "@/components/dashboard";

type GroundedInsight = { why: string; hook: string; format: string; payoff: string };

export function SearchPage({ initialQuery, initialItems = sampleVideos, sourceMode = "demo" }: { initialQuery: string; initialItems?: ShortVideo[]; sourceMode?: SourceMode }) {
  const [query, setQuery] = useState(initialQuery);
  const [submitted, setSubmitted] = useState(initialQuery);
  const results = useMemo(() => submitted ? initialItems.filter((video) => `${video.title} ${video.topic} ${video.category} ${video.channel} ${video.format}`.toLowerCase().includes(submitted.toLowerCase())) : [], [initialItems, submitted]);
  const adjacent = initialItems.filter((video) => !results.some((result) => result.id === video.id)).slice(0, Math.max(0, 4 - results.length));
  const visible = submitted ? [...results, ...adjacent].slice(0, 4) : [];
  const avgMomentum = visible.length ? Math.round(visible.reduce((total, video) => total + video.momentumScore, 0) / visible.length) : 0;
  const topTopics = Array.from(new Set(visible.flatMap((video) => [video.topic, video.format, video.category]))).slice(0, 5);
  return <>
    <PageIntro eyebrow="RADAR / NICHE INTELLIGENCE" title="Search a niche" description="Move from a broad idea to the Shorts, formats, and creator signals worth inspecting." />
    <form className="niche-search" onSubmit={(event) => { event.preventDefault(); setSubmitted(query.trim()); }}>
      <Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: budget travel, AI agents, college meals" aria-label="Search a niche" /><button className="primary-button" type="submit">Search signal</button>
    </form>
    <div className="search-suggestions"><span>Try a starting point</span>{["AI agents", "Delhi street food", "Beginner gym", "Student meals"].map((item) => <button key={item} type="button" onClick={() => { setQuery(item); setSubmitted(item); }}>{item}</button>)}</div>
    {submitted ? <><section className="radar-summary panel-surface"><div><p className="eyebrow">NICHE REPORT</p><h2>{submitted}</h2><p>{results.length ? "A focused signal set was found. Adjacent signals fill the report when the exact cluster is still thin." : "No exact cluster yet. Showing adjacent signals so the radar still has useful direction."}</p></div><div className="radar-score"><strong>{avgMomentum}</strong><span>avg momentum</span></div><div className="radar-tags">{topTopics.map((topic) => <span key={topic}>{topic}</span>)}</div></section><div className="result-meta"><span>{results.length} exact matches / {adjacent.length} adjacent signals for <strong>{submitted}</strong></span><span><span className="green-dot" /> {sourceMode === "live" ? "Observed YouTube evidence" : "Sample fixture"}</span></div><div className="video-grid reference-video-grid">{visible.map((video, index) => <ShortCard key={video.id} rank={index + 1} video={video} />)}</div></> : <div className="search-empty"><div className="search-empty-icon"><Search size={22} /></div><h2>Start with a market, format, or creator question.</h2><p>Search is the fastest way to move from a category to a useful content angle.</p></div>}
  </>;
}

export function DeepDivePage({ video }: { video: ShortVideo }) {
  const [tab, setTab] = useState<"why" | "dna" | "ideas">("why");
  const [saved, setSaved] = useState(false);
  const [insight, setInsight] = useState<GroundedInsight | null>(video.sourceMode === "demo" ? demoInsight(video) : null);
  const [insightError, setInsightError] = useState(false);

  useEffect(() => {
    if (video.sourceMode !== "live") return;
    let active = true;
    fetch(`/api/videos/${video.id}/insights`)
      .then((response) => response.ok ? response.json() as Promise<{ interpretation?: GroundedInsight }> : Promise.reject())
      .then((payload) => { if (active && payload.interpretation) setInsight(payload.interpretation); })
      .catch(() => { if (active) setInsightError(true); });
    return () => { active = false; };
  }, [video.id, video.sourceMode]);

  return <>
    <Link href="/trending" className="back-link">← What’s trending</Link>
    <div className="deep-dive-head"><div><p className="eyebrow">Trend deep dive / {video.sourceMode === "live" ? "Live source" : "Sample fixture"}</p><h1>{video.title}</h1><p className="deep-meta">{video.channel} <span>·</span> Published {video.publishedAt} <span>·</span> YouTube Shorts</p></div><div className="deep-actions"><button className={`quiet-button ${saved ? "save-active" : ""}`} onClick={() => setSaved(!saved)}><Bookmark size={14} fill={saved ? "currentColor" : "none"} /> {saved ? "Saved" : "Save"}</button><a href={video.sourceUrl} target="_blank" rel="noreferrer" className="quiet-button">Open source <ExternalLink size={13} /></a></div></div>
    <div className="deep-layout"><div><div className="deep-video" style={{ backgroundImage: `url(${displayThumbnail(video)})` }}><span className="deep-play"><Play size={20} fill="currentColor" /></span><span className="trend-badge trend-exploding">{video.label}</span></div><div className="evidence-note"><span className="green-dot" /><div><strong>Observed source data</strong><span>{video.sourceMode === "live" ? "Views, likes, comments, duration, and publish timing were observed from YouTube." : "Views, likes, comments, and publish timing are demo evidence, not current YouTube activity."}</span></div></div></div><aside className="score-panel panel-surface"><p className="eyebrow">Momentum score</p><div className="big-score">{video.momentumScore}<span>/100</span></div><div className="score-line"><span>Velocity estimate</span><strong>{video.velocity ? `+${video.velocity}%` : "First observation"}</strong></div><div className="score-line"><span>Views / hour</span><strong>{video.viewsPerHour.toLocaleString()}</strong></div><div className="score-line"><span>Engagement</span><strong>{video.engagement}%</strong></div><p className="score-note">Directional estimate. Historical momentum requires repeated observations.</p></aside></div>
    <div className="deep-tabs">{([["why", "Why this is trending"], ["dna", "Viral DNA"], ["ideas", "AI ideas"]] as const).map(([id, label]) => <button key={id} className={tab === id ? "deep-tab-active" : ""} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div className="deep-insight panel-surface">{tab === "why" && <><p className="eyebrow">AI interpretation / grounded in observed fields</p><h2>Why this is trending</h2>{insightError ? <p className="insight-lede">Grounded intelligence is temporarily unavailable. The observed evidence remains available above.</p> : <p className="insight-lede">{insight?.why ?? "Interpreting the observed evidence..."}</p>}<div className="insight-grid"><Insight label="Hook" value={insight?.hook ?? "Awaiting grounded interpretation"} /><Insight label="Format" value={insight?.format ?? video.format} /><Insight label="Viewer payoff" value={insight?.payoff ?? "Awaiting grounded interpretation"} /><Insight label="Evidence" value={`${video.views.toLocaleString()} views · ${video.likes.toLocaleString()} likes`} /></div></>}{tab === "dna" && <><p className="eyebrow">Pattern breakdown</p><h2>The repeatable mechanics</h2><div className="dna-list"><Dna label="Opening promise" text="A specific constraint is visible in the first second." /><Dna label="Tension" text="The audience mentally keeps the running total." /><Dna label="Payoff" text="The final result resolves the price question." /><Dna label="Evidence boundary" text="A single observation cannot prove historical growth." /></div></>}{tab === "ideas" && <><p className="eyebrow">Creator action</p><h2>Three directions worth making</h2><div className="idea-list"><Idea title="Make the format local" text="Keep the evidence-backed mechanic and adapt it to your own audience." /><Idea title="Change the constraint" text="Test a different price, time, or location while keeping the payoff visible." /><Idea title="Turn it into a series" text="Use the same format across three recognizable places or audiences." /></div><Link href="/ideas" className="primary-button">Open AI Ideas <ChevronRight size={14} /></Link></>}</div>
  </>;
}

export function IdeasPage({ video = sampleVideos[0], sourceMode = "demo" }: { video?: ShortVideo; sourceMode?: SourceMode }) {
  const [generated, setGenerated] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [ideas, setIdeas] = useState<{ title: string; rationale: string }[]>([]);
  async function generate() {
    setLoading(true); setError(false);
    try { const response = await fetch("/api/ideas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: video.id }) }); const payload = await response.json() as { ideas?: { title: string; rationale: string }[] }; if (!response.ok || !payload.ideas) throw new Error(); setIdeas(payload.ideas); setGenerated(true); } catch { setError(true); } finally { setLoading(false); }
  }
  return <><PageIntro eyebrow={`Creator action / ${sourceMode === "live" ? "Live source" : "Sample fixture"}`} title="Make the signal useful" description="Turn a momentum pattern into a creator-ready starting point without losing the evidence behind it." action={<button className="quiet-button" onClick={() => { setGenerated(false); setIdeas([]); }}><RefreshCw size={14} /> Reset</button>} /><div className="ideas-layout"><section className="idea-generator panel-surface"><p className="eyebrow">Your brief</p><h2>What do you want to make?</h2><textarea defaultValue={`A YouTube Short based on: ${video.title}`} aria-label="Content idea brief" /><div className="generator-row"><button className="primary-button" onClick={generate} disabled={loading}><PenLine size={15} /> {loading ? "Grounding ideas..." : "Generate ideas"}</button><span>{error ? "The grounded request failed. Try again." : "Uses observed signal evidence"}</span></div></section><section className="generated-ideas">{generated ? <><div className="section-heading"><div><p className="eyebrow">Grounded output</p><h2>Three angles with signal</h2></div><span className="sample-label">{ideas.length ? "Generated from evidence" : "No output"}</span></div><div className="idea-stack">{ideas.map((idea, index) => <IdeaCard key={idea.title} number={String(index + 1).padStart(2, "0")} title={idea.title} text={idea.rationale} tag="Evidence-backed direction" />)}</div></> : <div className="search-empty idea-empty"><div className="search-empty-icon"><PenLine size={22} /></div><h2>Start from a real signal.</h2><p>Generate creator angles from the current MOMENTUM evidence.</p><button className="primary-button" onClick={generate}>Generate ideas <ChevronRight size={14} /></button></div>}</section></div></>;
}

export function SavedPage() { const savedIds = JSON.parse(useSyncExternalStore(subscribeToSaved, savedSnapshot, savedServerSnapshot)) as string[]; const saved = sampleVideos.filter((video) => savedIds.includes(video.id)); return <><PageIntro eyebrow="Workspace / Your signals" title="Saved" description="Keep the Shorts, categories, and ideas you want to return to." action={<span className="sample-label">Local demo workspace</span>} />{saved.length ? <div className="video-grid">{saved.map((video, index) => <ShortCard key={video.id} rank={index + 1} video={video} saved onSave={() => writeSavedIds(savedIds.filter((id) => id !== video.id))} />)}</div> : <div className="empty-state saved-empty"><Bookmark size={19} /><h2>Nothing saved yet.</h2><p>Save a Short or category when you see a signal worth coming back to.</p><Link href="/trending" className="primary-button">Explore what’s trending <ChevronRight size={14} /></Link></div>}</>; }

export function PricingPage() { return <><PageIntro eyebrow="MOMENTUM / Plans" title="Pay for deeper signal, not more noise." description="Start with India-wide momentum. Upgrade when you need the history, context, and creator fit behind it." /><div className="pricing-grid">{plans.map((plan) => <article key={plan.id} className={`pricing-card ${plan.id === "creator" ? "pricing-featured" : ""}`}>{plan.id === "creator" && <span className="plan-recommended">Most useful for creators</span>}<p className="eyebrow">{plan.name}</p><h2>{plan.price}<small>{plan.id !== "free" && "/ month"}</small></h2><p className="plan-description">{plan.description}</p><button className={plan.id === "creator" ? "primary-button" : "quiet-button"}>{plan.id === "free" ? "Current plan" : "Unlock intelligence"} <ChevronRight size={14} /></button><div className="plan-features">{plan.features.map((feature) => <span key={feature}><Check size={13} /> {feature}</span>)}</div></article>)}</div><p className="pricing-note">Billing is not connected in this demo. Plan boundaries are product architecture, not a claim of paid access.</p></>; }

export function SettingsPage() { const usage = getDailyUsage(); return <><PageIntro eyebrow="Workspace / Preferences" title="Settings" description="Keep the radar focused on the market and formats you care about." /><div className="settings-layout"><div className="settings-nav"><button className="settings-active">Profile</button><button>Appearance</button><button>Region</button><button>Preferences</button><button>Usage</button><button>Plan</button><button>About</button></div><section className="settings-panel panel-surface"><div className="settings-section"><p className="eyebrow">Profile</p><h2>Make the signal yours.</h2><label>Display name<input defaultValue="A creator exploring India" /></label><label>Creator focus<select defaultValue="Just exploring"><option>Just exploring</option><option>Food creator</option><option>Travel creator</option><option>Business</option><option>Brand</option></select></label></div><div className="settings-section"><p className="eyebrow">Radar</p><h2>Where should MOMENTUM look?</h2><div className="setting-row"><div><strong>Market</strong><span>India</span></div><span className="locked-pill"><Check size={12} /> Available</span></div><div className="setting-row"><div><strong>City intelligence</strong><span>Local signals are the next layer.</span></div><button className="locked-pill" onClick={() => alert("City intelligence is coming soon.")}><LockKeyhole size={11} /> Locked</button></div></div><div className="settings-section"><p className="eyebrow">Usage</p><h2>Today’s scan budget</h2><div className="usage-large"><div><strong>{usage.used}</strong><span>of {usage.limit} free trends used</span></div><div className="usage-track"><span style={{ width: `${usage.used / usage.limit * 100}%` }} /></div></div></div></section></div></>; }

function demoInsight(video: ShortVideo): GroundedInsight { return { why: video.why, hook: "Can you do it with only the constraint?", format: video.format, payoff: "A visible final reveal" }; }
function displayThumbnail(video: ShortVideo): string { return video.thumbnail.startsWith("/") ? video.thumbnail : `/api/thumbnail?url=${encodeURIComponent(video.thumbnail)}`; }
function Insight({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Dna({ label, text }: { label: string; text: string }) { return <div className="dna-row"><span className="dna-index">+</span><div><strong>{label}</strong><p>{text}</p></div></div>; }
function Idea({ title, text }: { title: string; text: string }) { return <div className="idea-row"><div><strong>{title}</strong><p>{text}</p></div><button className="icon-button" aria-label={`Copy ${title}`} title="Copy idea"><Copy size={14} /></button></div>; }
function IdeaCard({ number, title, text, tag }: { number: string; title: string; text: string; tag: string }) { return <article className="idea-card"><span className="idea-number">{number}</span><div><h3>{title}</h3><p>{text}</p><span className="idea-tag">{tag}</span></div><button className="icon-button" aria-label="Save idea" title="Save idea"><Bookmark size={14} /></button></article>; }
