import type { Category, ShortVideo } from "@/lib/types";

export const sampleVideos: ShortVideo[] = [
  { id: "short-01", title: "I tried the ₹100 street food challenge in Delhi", channel: "The Hungry Indian", thumbnail: "/thumbs/short-01.jpg", category: "Food", topic: "Street food challenges", format: "Budget challenge", publishedAt: "2h ago", durationSeconds: 38, views: 482000, likes: 38700, comments: 1820, viewsPerHour: 31000, engagement: 8.4, momentumScore: 87, velocity: 112, label: "Exploding", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "A clear money constraint creates instant stakes, while the visible payoff makes the format easy to understand and reproduce." },
  { id: "short-02", title: "Can a tourist eat Mumbai for ₹200?", channel: "Wander With Riya", thumbnail: "/thumbs/short-02.jpg", category: "Travel", topic: "Budget travel", format: "Tourist vs local", publishedAt: "5h ago", durationSeconds: 44, views: 318000, likes: 26500, comments: 934, viewsPerHour: 27800, engagement: 8.6, momentumScore: 82, velocity: 76, label: "Rising", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "The contrast between outsider expectations and local knowledge gives viewers a simple reason to stay until the final reveal." },
  { id: "short-03", title: "The 10-minute desk workout that actually hurts", channel: "Move Better Daily", thumbnail: "/thumbs/short-03.jpg", category: "Fitness", topic: "Desk workouts", format: "Timed challenge", publishedAt: "7h ago", durationSeconds: 29, views: 207000, likes: 18100, comments: 620, viewsPerHour: 19600, engagement: 9.1, momentumScore: 78, velocity: 64, label: "Rising", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "A familiar pain point, a visible timer, and a low equipment barrier combine into a highly repeatable utility format." },
  { id: "short-04", title: "I let an AI agent plan my entire Sunday", channel: "Build With Arjun", thumbnail: "/thumbs/short-04.jpg", category: "AI & Tech", topic: "AI agents", format: "Real-world experiment", publishedAt: "9h ago", durationSeconds: 51, views: 164000, likes: 15400, comments: 1100, viewsPerHour: 15200, engagement: 10.1, momentumScore: 75, velocity: 51, label: "Emerging", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "The idea turns an abstract technology into a personal experiment with a clear before-and-after narrative." },
  { id: "short-05", title: "One pan, three college meals under ₹80", channel: "Campus Cooks", thumbnail: "/thumbs/short-05.jpg", category: "Food", topic: "Student meals", format: "Constraint recipe", publishedAt: "11h ago", durationSeconds: 34, views: 141000, likes: 12900, comments: 480, viewsPerHour: 12700, engagement: 9.5, momentumScore: 72, velocity: 44, label: "Emerging", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "A tight constraint compresses the story and gives a practical audience a reason to save and share the result." },
  { id: "short-06", title: "What ₹500 gets you in Old Delhi at midnight", channel: "After Hours India", thumbnail: "/thumbs/short-06.jpg", category: "Travel", topic: "Night markets", format: "Price reveal", publishedAt: "13h ago", durationSeconds: 46, views: 118000, likes: 10400, comments: 361, viewsPerHour: 8800, engagement: 9.1, momentumScore: 69, velocity: 39, label: "Emerging", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "The price-led title sets a concrete expectation and the location adds a sense of discovery without needing context." },
  { id: "short-07", title: "The beginner gym mistakes nobody tells you", channel: "Strong Start India", thumbnail: "/thumbs/short-07.jpg", category: "Fitness", topic: "Beginner gym", format: "Mistake breakdown", publishedAt: "1d ago", durationSeconds: 42, views: 92000, likes: 8100, comments: 290, viewsPerHour: 4100, engagement: 9.1, momentumScore: 64, velocity: 28, label: "Steady", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "Specific, corrective advice gives a new audience an immediate identity and creates a natural save intent." },
  { id: "short-08", title: "I rebuilt a useful app in 30 minutes with AI", channel: "Code In Public", thumbnail: "/thumbs/short-08.jpg", category: "AI & Tech", topic: "AI coding", format: "Build in public", publishedAt: "1d ago", durationSeconds: 56, views: 86000, likes: 7400, comments: 514, viewsPerHour: 3800, engagement: 9.2, momentumScore: 61, velocity: 22, label: "Steady", sourceMode: "demo", sourceUrl: "https://www.youtube.com/shorts/", why: "A visible time limit makes the build legible to non-developers and turns process into a satisfying payoff." },
];

export const categories: Category[] = [
  { slug: "ai-tech", name: "AI & Tech", description: "Tools, agents, and workflows moving through the creator economy.", color: "#a8f26b", momentum: 68, videoCount: 1240, subtopics: [{ name: "AI Agents", change: "+64%", status: "Exploding" }, { name: "AI Coding", change: "+51%", status: "Rising" }, { name: "Creator Tools", change: "+39%", status: "Emerging" }] },
  { slug: "gaming", name: "Gaming", description: "Formats, challenges, and moments shaping Indian gaming culture.", color: "#d3a8ff", momentum: 61, videoCount: 982, subtopics: [{ name: "Challenge Runs", change: "+42%", status: "Rising" }, { name: "Mobile Esports", change: "+31%", status: "Emerging" }, { name: "Game Reactions", change: "+18%", status: "Steady" }] },
  { slug: "entertainment", name: "Entertainment", description: "Reaction, remix, and personality formats finding new audiences.", color: "#ffca79", momentum: 59, videoCount: 1840, subtopics: [{ name: "Street Interviews", change: "+47%", status: "Rising" }, { name: "Pop Culture", change: "+29%", status: "Emerging" }, { name: "Reaction Loops", change: "+21%", status: "Steady" }] },
  { slug: "food", name: "Food", description: "Recipes, budget challenges, and the formats people save for later.", color: "#ff8c8c", momentum: 57, videoCount: 1520, subtopics: [{ name: "Budget Challenges", change: "+72%", status: "Exploding" }, { name: "Street Food", change: "+38%", status: "Rising" }, { name: "One-Pan Recipes", change: "+24%", status: "Emerging" }] },
  { slug: "fitness", name: "Fitness", description: "Practical routines and visible transformations built for repeat viewing.", color: "#84d8ff", momentum: 52, videoCount: 740, subtopics: [{ name: "Desk Workouts", change: "+55%", status: "Rising" }, { name: "Beginner Gym", change: "+31%", status: "Emerging" }, { name: "Mobility", change: "+20%", status: "Steady" }] },
];

export const cityOptions = ["Delhi NCR", "Mumbai", "Bengaluru", "Hyderabad", "Pune", "Chennai"] as const;

export function getVideo(id: string): ShortVideo {
  return sampleVideos.find((video) => video.id === id) ?? sampleVideos[0];
}

export function getCategory(slug: string): Category {
  return categories.find((category) => category.slug === slug) ?? categories[0];
}
